---
abstract: 'run perltidy and podtidy before Git commits'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  FindBin: 0
  Path::Tiny: 0
  Sys::Cmd: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-githook-perltidy
no_index:
  directory:
    - inc
    - t
    - xt
  package:
    - App::githook_perltidy::Util
    - App::githook_perltidy::install
    - App::githook_perltidy::pre_commit
    - App::githook_perltidy::post_commit
requires:
  Carp: 0
  Exporter::Tidy: 0
  File::Basename: 0
  OptArgs: 0
  Path::Tiny: 0
  Perl::Tidy: 0
  Pod::Tidy: 0
  Time::Piece: 0
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/mlawren/githook-perltidy.git
version: 0.11.5_1
